name: "Validate OSV"

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: "1.20"
    - name: Validate
      run: make validate
